version: "3"
services:
  postgres:
    image: "registry.hub.docker.com/caedus41/oreilly-cloud-engineer-postgres:latest"
    volumes: 
      - db-data:/var/lib/postgres/data
    env_file:
      - ./postgres.env
    expose:
      - "5432"
  ormapi:
    image: "nysyr/orm_search:latest"
    #image: "nysyr/orm_search:searchtest"
    env_file:
     - ./api.env
    ports: 
      - "8000:5000"
    links: 
      - postgres
    depends_on:
      - postgres
volumes: 
  db-data: