apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orm-api
  name: orm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orm-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: orm-api
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: api-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: api-env
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_URL
                  name: api-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: api-env
          image: registry.hub.docker.com/nysyr/orm_search:latest
          name: orm-api
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
